"""Generate the type-14 connection from the production BSSN definitions.
Run from any directory; the checked-in include needs no runtime Python.
"""
from contextlib import redirect_stdout
from pathlib import Path
import dendro

gt = dendro.sym_3x3('gt', '[pp]')
dendro.set_first_derivative('grad')
dendro.set_metric(gt)
inv = dendro.get_inverse_metric()
dendro.get_first_christoffel()
c2 = dendro.get_second_christoffel()
connection = [sum(inv[j,k]*c2[i,j,k] for j,k in dendro.e_ij)
              for i in dendro.e_i]
path = Path(__file__).resolve().parents[1] / 'BSSN_GR/scripts/teuk_connection.inc'
with path.open('w') as out, redirect_stdout(out):
    print('// Generated by CodeGen/teuk_connection.py using production dendro.py.')
    dendro.generate_cpu([connection], ['connection'], '[pp]')
