##
# @brief: SECOND-ORDER shift-driver worldtube config: evaluates Dendro-GR's
#          compiled-in Gamma-driver eta prescription at a fixed radius, for
#          use as SpECTRE CCE's `SecondOrderDriverEta` when preprocessing a
#          CCE worldtube written by Dendro-GR.
# @date: 2026-09-16 (renamed from cce_worldtube_eta.py; see cce_worldtube_first.py
#          for the sibling FIRST-order driver path)
#
# Context: SpECTRE's `PreprocessCceWorldtube` (AdmMetricNodal) supports two
# mutually-exclusive ways to reconstruct the shift's time derivative -- see
# cce_worldtube_first.py for the first-order (auxiliary shift B^i) path,
# which is currently under review by a group member for the Gt^i (conformal
# Christoffel) side of things. THIS script covers the second-order path,
# which reconstructs
#     d(beta^i)/dt = ConformalChristoffelFactor * Gt^i - SecondOrderDriverEta * beta^i
# assuming SecondOrderDriverEta is a single constant. Dendro-GR's actual
# eta is NOT a constant -- as compiled in BSSN_GR/src/rhs.cpp (which
# #includes "eta_RIT.inc.cpp", all other eta_*.inc.cpp variants are
# commented out there), it is the RIT prescription:
#
#     w   = r / RIT_ETA_WIDTH
#     eta = (RIT_ETA_CENTRAL - RIT_ETA_OUTER) * exp(-w**4) + RIT_ETA_OUTER
#
# (BSSN_GR/src/eta_RIT.inc.cpp). Since a CCE worldtube sits at one fixed
# coordinate radius, eta only needs to be evaluated once, at that radius,
# using whatever RIT_ETA_CENTRAL/OUTER/WIDTH the run actually used -- this
# script does that, and can optionally emit a ready-to-use
# PreprocessCceWorldtube.yaml (mirroring SpECTRE's own
# tests/InputFiles/PreprocessCceWorldtube/AdmSecondOrderDriverPreprocessCceWorldtube.yaml).
#
# Defaults for RIT_ETA_CENTRAL/OUTER/WIDTH match Dendro-GR's compiled-in
# defaults (BSSN_GR/src/parameters.cpp), which are NOT overridden in the
# sample q1/q4/q8 .par.toml configs. Pass --par-file to auto-extract
# overrides from an actual parameter file instead of relying on defaults.
#
# NOTE: see the CCE writeup (Dendro_CCE_v1.3.md, Section 6.2 / Appendix)
# for why the first-order shift driver (cce_worldtube_first.py -- using
# Dendro-GR's natively-evolved auxiliary shift B^i directly, no eta
# involved at all) may be a structurally better default than this
# second-order/eta path -- Dendro-GR does not have any analogue of
# ConformalChristoffelFactor as a distinct, separately-tunable quantity.
# Both scripts are kept and maintained since the choice between the two
# driver formulations is still under discussion within the group.

import argparse
import math
import re
import sys

# compiled-in defaults, BSSN_GR/src/parameters.cpp
DEFAULT_RIT_ETA_CENTRAL = 2.0
DEFAULT_RIT_ETA_OUTER = 0.25
DEFAULT_RIT_ETA_WIDTH = 40.0


def rit_eta(r, eta_central=DEFAULT_RIT_ETA_CENTRAL,
            eta_outer=DEFAULT_RIT_ETA_OUTER,
            eta_width=DEFAULT_RIT_ETA_WIDTH):
    '''
    @brief Evaluates Dendro-GR's compiled-in RIT eta prescription at
           coordinate radius r (in units of total mass M, matching the
           mass-normalized convention used in Dendro-GR's sample configs).
           Exact translation of BSSN_GR/src/eta_RIT.inc.cpp.
    '''
    w = r / eta_width
    return (eta_central - eta_outer) * math.exp(-(w ** 4)) + eta_outer


def extract_eta_params_from_par_file(path):
    '''
    @brief Lightweight regex-based extraction of RIT_ETA_CENTRAL/OUTER/WIDTH
           overrides from a Dendro-GR .par.toml or .par.json file, without
           requiring a toml/json parser dependency. Returns a dict with only
           the keys actually found in the file (missing keys keep the
           compiled-in default in the caller).
    '''
    found = {}
    key_map = {
        'RIT_ETA_CENTRAL': 'eta_central',
        'RIT_ETA_OUTER': 'eta_outer',
        'RIT_ETA_WIDTH': 'eta_width',
    }
    with open(path, 'r') as f:
        text = f.read()
    for toml_key, arg_name in key_map.items():
        match = re.search(toml_key + r'\s*[:=]\s*([0-9.eE+-]+)', text)
        if match:
            found[arg_name] = float(match.group(1))
    return found


YAML_TEMPLATE = """\
# Generated by cce_worldtube_second.py -- Dendro-GR -> SpECTRE CCE worldtube
# preprocessing config. Mirrors SpECTRE's own
# tests/InputFiles/PreprocessCceWorldtube/AdmSecondOrderDriverPreprocessCceWorldtube.yaml,
# with SecondOrderDriverEta evaluated from Dendro-GR's actual compiled-in
# RIT eta prescription (BSSN_GR/src/eta_RIT.inc.cpp) at the extraction
# radius below, instead of SpECTRE's example placeholder value.

InputH5File: {input_h5}
OutputH5File: {output_h5}
InputDataFormat:
  AdmMetricNodal:
    Lapse:
      Advective: True
    Shift:
      Advective: True
      ConformalChristoffelFactor: {conformal_christoffel_factor} # Eq. 12 Hilditch 2013 -- no direct Dendro-GR analogue, see script docstring
      SecondOrderDriverEta: {eta:.10g} # RIT prescription evaluated at r={radius:g}M (eta_central={eta_central:g}, eta_outer={eta_outer:g}, eta_width={eta_width:g})
ExtractionRadius: {radius:g}
FixSpecNormalization: False
DescendingM: False
BufferDepth: Auto
LMaxFactor: {lmax_factor:g}
"""


def main():
    parser = argparse.ArgumentParser(
        description='Evaluate Dendro-GR\'s compiled-in RIT eta prescription '
                     'at a fixed worldtube radius, for SpECTRE CCE\'s '
                     'SecondOrderDriverEta, and optionally emit a ready-to-use '
                     'PreprocessCceWorldtube.yaml.')
    parser.add_argument('--radius', type=float, required=True,
                         help='Worldtube/extraction coordinate radius, in '
                              'units of total mass M (e.g. 100 for a 100M '
                              'worldtube, matching Dendro-GR\'s mass-'
                              'normalized sample configs).')
    parser.add_argument('--eta-central', type=float, default=None,
                         help='Override RIT_ETA_CENTRAL (default: compiled-in '
                              'Dendro-GR default, %g).' % DEFAULT_RIT_ETA_CENTRAL)
    parser.add_argument('--eta-outer', type=float, default=None,
                         help='Override RIT_ETA_OUTER (default: compiled-in '
                              'Dendro-GR default, %g).' % DEFAULT_RIT_ETA_OUTER)
    parser.add_argument('--eta-width', type=float, default=None,
                         help='Override RIT_ETA_WIDTH (default: compiled-in '
                              'Dendro-GR default, %g).' % DEFAULT_RIT_ETA_WIDTH)
    parser.add_argument('--par-file', type=str, default=None,
                         help='Path to a Dendro-GR .par.toml/.par.json to '
                              'auto-extract RIT_ETA_CENTRAL/OUTER/WIDTH '
                              'overrides from, if present (explicit '
                              '--eta-* flags above still take precedence).')
    parser.add_argument('--write-yaml', type=str, default=None,
                         help='If given, write a full PreprocessCceWorldtube.yaml '
                              'to this path with the computed eta plugged in.')
    parser.add_argument('--input-h5', type=str, default='InputFilename.h5',
                         help='InputH5File value for --write-yaml (default: '
                              'placeholder, edit before use).')
    parser.add_argument('--output-h5', type=str, default=None,
                         help='OutputH5File value for --write-yaml (default: '
                              'derived from --radius, e.g. ReducedWorldtubeR0100.h5).')
    parser.add_argument('--conformal-christoffel-factor', type=float, default=1.0,
                         help='ConformalChristoffelFactor value for --write-yaml '
                              '(default: 1.0, SpECTRE\'s own example value -- '
                              'Dendro-GR has no directly-derived analogue for '
                              'this quantity, see script docstring).')
    parser.add_argument('--lmax-factor', type=float, default=3,
                         help='LMaxFactor value for --write-yaml (default: 3).')
    args = parser.parse_args()

    eta_central = DEFAULT_RIT_ETA_CENTRAL
    eta_outer = DEFAULT_RIT_ETA_OUTER
    eta_width = DEFAULT_RIT_ETA_WIDTH

    if args.par_file:
        overrides = extract_eta_params_from_par_file(args.par_file)
        eta_central = overrides.get('eta_central', eta_central)
        eta_outer = overrides.get('eta_outer', eta_outer)
        eta_width = overrides.get('eta_width', eta_width)

    if args.eta_central is not None:
        eta_central = args.eta_central
    if args.eta_outer is not None:
        eta_outer = args.eta_outer
    if args.eta_width is not None:
        eta_width = args.eta_width

    eta = rit_eta(args.radius, eta_central, eta_outer, eta_width)

    print('RIT eta prescription parameters: '
          'eta_central=%g, eta_outer=%g, eta_width=%g'
          % (eta_central, eta_outer, eta_width))
    print('eta(r=%gM) = %.10g' % (args.radius, eta))

    if args.write_yaml:
        output_h5 = args.output_h5 or (
            'ReducedWorldtubeR%04d.h5' % round(args.radius))
        yaml_text = YAML_TEMPLATE.format(
            input_h5=args.input_h5,
            output_h5=output_h5,
            conformal_christoffel_factor=args.conformal_christoffel_factor,
            eta=eta,
            radius=args.radius,
            eta_central=eta_central,
            eta_outer=eta_outer,
            eta_width=eta_width,
            lmax_factor=args.lmax_factor,
        )
        with open(args.write_yaml, 'w') as f:
            f.write(yaml_text)
        print('Wrote %s' % args.write_yaml)


if __name__ == '__main__':
    sys.exit(main())
